### ISSUE TITLE
Feature/Submit an advice

### ISSUE THREAD

**Issue by CerineBnsd** [GDGAlgiers/BrainyBot#34]
### Context

GDG Algiers' discord community members love getting advice from the bots there. Brainy's ones are brilliant, yet we almost have seen all of them and the funny  command has started losing its shine.
In order to get it back, we need more advice in the set. 

The idea is to let the community members contribute with their own piece of advice and to make this process less technical than doing pull requests.

### Proposition

Creating a new command that enables a member in the server to submit an advice that will be added to the list. It is important to include a validation step in the process, to avoid adding irrelevant advice or inappropriate ones. 

### The suggested workflow

1. The user runs the command in Brainy's DM in this format : 

`    $submit <the advice> `

2.  The user gets a message confirming the receipt of the advice and saying that it will be validated soon.
3. The person in charge of validation is notified and is able to validate the advice or reject it.
4. The user receives a message with the result of the validation.
5. The advice is added to the set, if validated.

### Remaining issues

- The validation step is mandatory to preserve the community guidelines, yet since it had to be manual, it can be overwhelming for the person in charge. How can we make it less annoying ?

### Tasks

- [ ]  Propose a workflow for the validation step
- [ ]  Write the code for the new command
- [ ]  Test the functioning
- [ ]  Release it

**Comment by akram09** [comment]
Hello There, I think it's a very awesome Idea to allow community members to contribute to our advice space. As we are currently using a google sheet for storing advice I think we should now try moving to database access to better organize it? 
For the review and validation part, I thought about having a channel that serves as a log for all the feature submissions and moderators can validate, cancel or edit a submission. What do you think about it @CerineBnsd @Aymen311 ?

**Comment by CerineBnsd** [comment]
Hello Akram! thanks for the your suggestions, I think they are great and should be taken into consideration while developing this feature.
